name: B2W Est API
values:
  - key: BaseURL
    value: ""
    enabled: true
  - key: ConnectionString
    value: ""
    enabled: true
  - key: Token
    value: ""
    enabled: true
  - key: UserName
    value: ""
    enabled: true
  - key: Password
    value: ""
    enabled: true
  - key: ClientID
    value: ""
    enabled: true
  - key: ClientSecret
    value: ""
    enabled: true
color: 0
