// Client-safe column schema (no server imports)

export const AVAILABLE_COLUMNS = [
  { key: "date", label: "Target Date", type: "date" },
  { key: "sourceEntity", label: "Source Entity", type: "string" },
  { key: "targetQuantity", label: "Target Quantity", type: "number" },
  { key: "trackingId", label: "Tracking ID", type: "string" },
  { key: "jobNumber", label: "Job Number", type: "string" },
  { key: "projectManagerId", label: "Project Manager ID", type: "string" },
  { key: "projectManagerName", label: "Project Manager Name", type: "string" },
  { key: "siteSupervisorEmployeeId", label: "Site Supervisor Employee ID", type: "string" },
  { key: "siteSupervisorName", label: "Site Supervisor Name", type: "string" },
  { key: "itemId", label: "Item ID", type: "string" },
  { key: "itemNumber", label: "Item Number", type: "string" },
  { key: "originalUnitBidPrice", label: "Original Unit Bid Price", type: "number" },
  { key: "originalTotalBidPrice", label: "Original Total Bid Price", type: "number" },
  { key: "changeOrderUnitBidPrice", label: "Change Order Unit Bid Price", type: "number" },
  { key: "changeOrderTotalBidPrice", label: "Change Order Total Bid Price", type: "number" },
  { key: "costBreakdownElementId", label: "Cost Breakdown Element ID", type: "string" },
  { key: "estimatedQuantity", label: "Estimated Quantity", type: "number" },
  { key: "totalEmployeeDollars", label: "Total Employee Dollars", type: "number" },
  { key: "totalEquipmentOwnedDollars", label: "Total Equipment Owned Dollars", type: "number" },
  { key: "totalSubcontractorDollars", label: "Total Subcontractor Dollars", type: "number" },
  { key: "totalTruckingDollars", label: "Total Trucking Dollars", type: "number" },
  { key: "crewId", label: "Crew ID", type: "string" },
  { key: "crewForemanEmployeeId", label: "Crew Foreman", type: "string" },
  { key: "crewForemanName", label: "Crew Foreman Name", type: "string" },
  { key: "crewWorkType", label: "Crew Work Type", type: "string" },
  { key: "crewSize", label: "Crew Size", type: "number" },
  { key: "duration", label: "Duration (hrs)", type: "number" },
  { key: "productionMethod", label: "Production Method", type: "string" },
  { key: "targetMethod", label: "Target Method", type: "string" },
  { key: "productionRate", label: "Production Rate", type: "number" },
  { key: "notes", label: "Notes", type: "string" },
  { key: "jobSiteDescription", label: "Job Site Description", type: "string" },
  { key: "unitOfMeasure", label: "Unit of Measure", type: "string" },
  { key: "originalEstimatedQuantity", label: "Original Est. Qty", type: "number" },
  { key: "changeOrderQuantity", label: "Change Order Qty", type: "number" },
  { key: "projectedTotalQuantity", label: "Projected Total Qty", type: "number" },
  { key: "description", label: "Account Description", type: "string" },
] as const;

export type ColumnKey = (typeof AVAILABLE_COLUMNS)[number]["key"];
